name = "atenra"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"


[[d1_databases]]
binding = "DATABASE"
database_name = "atenra-dev-db"
database_id = "7ed327c0-e838-4fd5-8369-a6b5e90dd04d"
migrations_dir = "./drizzle"
