name = "atenra"
compatibility_date = "2024-09-03"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"

[placement]
mode = "smart"

[[d1_databases]]
binding = "DATABASE"
database_name = "atenra-db"
database_id = "542ba0c5-8c8b-4c70-876b-18acd264346d"
migrations_dir = "./drizzle"
